# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Depoto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  # Pods for Depoto
  pod 'GoogleMaps', '2.5.0'
  pod 'Google-Maps-iOS-Utils'

end
